# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestInteraccionchatbot():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}
  
    def teardown_method(self, method):
        self.driver.quit()
  
    def test_interaccionchatbot(self):
        self.driver.get("http://localhost:5000/login")
        self.driver.set_window_size(1536, 816)
        self.driver.find_element(By.ID, "correo").click()
        self.driver.find_element(By.ID, "correo").send_keys("gustavo@gmail.com")
        self.driver.find_element(By.ID, "password").send_keys("gustavo")
        self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
        self.driver.find_element(By.CSS_SELECTOR, "svg").click()
        self.driver.find_element(By.ID, "chat-input").click()
        self.driver.find_element(By.ID, "chat-input").send_keys("hola")
        self.driver.find_element(By.ID, "send-button").click()
        
        # Aquí mueve el puntero sobre el botón de enviar
        element = self.driver.find_element(By.ID, "send-button")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        
        # Mueve el puntero sobre el body
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        
        # Interacción con el chat (completando el flujo de mensajes)
        self.driver.find_element(By.ID, "chat-input").click()
        self.driver.find_element(By.ID, "chat-input").send_keys("asistencia")
        self.driver.find_element(By.ID, "send-button").click()
        
        element = self.driver.find_element(By.ID, "send-button")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        
        self.driver.find_element(By.ID, "chat-input").click()
        self.driver.find_element(By.ID, "chat-input").send_keys("gustavo@gmail.com")
        self.driver.find_element(By.ID, "chat-input").click()
        self.driver.find_element(By.ID, "chat-input").send_keys("gustavo@gmail.com gustavo")
        self.driver.find_element(By.ID, "send-button").click()
        
        self.driver.execute_script("window.scrollTo(0,0)")
        
        self.driver.find_element(By.ID, "chat-input").click()
        self.driver.find_element(By.ID, "chat-input").send_keys("si")
        self.driver.find_element(By.ID, "chat-input").send_keys(Keys.ENTER)
